# Generated by Django 4.2.7 on 2025-10-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_log',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_agents', models.BooleanField(default=True)),
                ('can_manage_templates', models.BooleanField(default=True)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_edit_global_templates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admins',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_capacity', models.IntegerField(default=15)),
                ('current_active_tickets', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline'), ('on_break', 'On Break')], default='offline', max_length=20)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_messages_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agents',
            },
        ),
        migrations.CreateModel(
            name='AgentDelayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_start_time', models.DateTimeField()),
                ('delay_end_time', models.DateTimeField(blank=True, null=True)),
                ('delay_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'agent_delay_events',
            },
        ),
        migrations.CreateModel(
            name='AgentKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_date', models.DateField()),
                ('total_tickets', models.IntegerField(default=0)),
                ('closed_tickets', models.IntegerField(default=0)),
                ('avg_response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('delay_count', models.IntegerField(default=0)),
                ('customer_satisfaction_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('first_response_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resolution_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('overall_kpi_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_kpi',
            },
        ),
        migrations.CreateModel(
            name='AgentKPIMonthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_tickets', models.IntegerField(default=0)),
                ('closed_tickets', models.IntegerField(default=0)),
                ('avg_response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('messages_sent', models.IntegerField(default=0)),
                ('messages_received', models.IntegerField(default=0)),
                ('delay_count', models.IntegerField(default=0)),
                ('avg_customer_satisfaction', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('overall_kpi_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_kpi_monthly',
            },
        ),
        migrations.CreateModel(
            name='AgentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'agent_templates',
            },
        ),
        migrations.CreateModel(
            name='AutoReplyTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_keyword', models.CharField(max_length=100)),
                ('reply_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('keyword', 'Keyword'), ('category', 'Category'), ('greeting', 'Greeting')], default='keyword', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auto_reply_triggers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('wa_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('sick', 'Sick'), ('needs_visits', 'Needs Visits')], default='regular', max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('total_tickets_count', models.IntegerField(default=0)),
                ('first_contact_date', models.DateTimeField(auto_now_add=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customers',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('admin', 'Admin'), ('system', 'System')], max_length=10)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('video', 'Video'), ('file', 'File'), ('interactive', 'Interactive'), ('template', 'Template')], default='text', max_length=20)),
                ('media_url', models.CharField(blank=True, max_length=500, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('whatsapp_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_forwarded', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('delayed', 'Delayed'), ('closed', 'Closed')], default='open', max_length=10)),
                ('category', models.CharField(choices=[('medicine_order', 'Medicine Order'), ('complaint', 'Complaint'), ('consultation', 'Consultation'), ('follow_up', 'Follow Up'), ('general', 'General')], default='general', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('is_delayed', models.BooleanField(default=False)),
                ('delay_started_at', models.DateTimeField(blank=True, null=True)),
                ('total_delay_minutes', models.IntegerField(default=0)),
                ('delay_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_agent_message_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('handling_time_seconds', models.IntegerField(blank=True, null=True)),
                ('messages_count', models.IntegerField(default=0)),
                ('closure_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='conversations.agent')),
            ],
            options={
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent')], max_length=10)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['role'], name='users_role_0ace22_idx'), models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'), models.Index(fields=['is_online'], name='users_is_onli_f24b46_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='conversations.agent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='conversations.ticket')),
                ('to_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='conversations.agent')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.user')),
            ],
            options={
                'db_table': 'ticket_transfers_log',
            },
        ),
        migrations.CreateModel(
            name='TicketStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_state', models.CharField(blank=True, max_length=50, null=True)),
                ('new_state', models.CharField(max_length=50)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.user')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_changes', to='conversations.ticket')),
            ],
            options={
                'db_table': 'ticket_states_log',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tickets', to='conversations.user'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='current_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_tickets', to='conversations.agent'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='conversations.customer'),
        ),
        migrations.CreateModel(
            name='ResponseTimeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_received_at', models.DateTimeField()),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('is_delayed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.agent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_tracking', to='conversations.ticket')),
            ],
            options={
                'db_table': 'response_time_tracking',
            },
        ),
        migrations.CreateModel(
            name='MessageSearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.customer')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.message')),
            ],
            options={
                'db_table': 'message_search_index',
            },
        ),
        migrations.CreateModel(
            name='MessageDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='conversations.message')),
            ],
            options={
                'db_table': 'message_delivery_log',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversations.ticket'),
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login_attempts',
                'indexes': [models.Index(fields=['username'], name='login_attem_usernam_7d95c4_idx'), models.Index(fields=['ip_address'], name='login_attem_ip_addr_0a65f5_idx'), models.Index(fields=['attempt_time'], name='login_attem_attempt_a9104a_idx'), models.Index(fields=['success'], name='login_attem_success_e73d81_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlobalTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to='conversations.admin')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_templates', to='conversations.admin')),
            ],
            options={
                'db_table': 'global_templates',
            },
        ),
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='conversations.customer')),
            ],
            options={
                'db_table': 'customer_tags',
            },
        ),
        migrations.CreateModel(
            name='CustomerSatisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.agent')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_ratings', to='conversations.ticket')),
            ],
            options={
                'db_table': 'customer_satisfaction',
            },
        ),
        migrations.CreateModel(
            name='CustomerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.user')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='conversations.customer')),
            ],
            options={
                'db_table': 'customer_notes',
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_number'], name='customers_phone_n_7d2329_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['wa_id'], name='customers_wa_id_cb464d_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['customer_type'], name='customers_custome_3f7c53_idx'),
        ),
        migrations.AddField(
            model_name='autoreplytrigger',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversations.admin'),
        ),
        migrations.AddField(
            model_name='autoreplytrigger',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.globaltemplate'),
        ),
        migrations.AddField(
            model_name='agenttemplate',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='conversations.agent'),
        ),
        migrations.AddField(
            model_name='agentkpimonthly',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_kpis', to='conversations.agent'),
        ),
        migrations.AddField(
            model_name='agentkpi',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_kpis', to='conversations.agent'),
        ),
        migrations.AddField(
            model_name='agentdelayevent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_events', to='conversations.agent'),
        ),
        migrations.AddField(
            model_name='agentdelayevent',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_events', to='conversations.ticket'),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='conversations.user'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='conversations.user'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conversations.user'),
        ),
        migrations.AddIndex(
            model_name='tickettransferlog',
            index=models.Index(fields=['ticket'], name='ticket_tran_ticket__fbde5a_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettransferlog',
            index=models.Index(fields=['created_at'], name='ticket_tran_created_88f804_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatelog',
            index=models.Index(fields=['ticket'], name='ticket_stat_ticket__7d3037_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketstatelog',
            index=models.Index(fields=['created_at'], name='ticket_stat_created_69a14b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_status_fbbf05_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_agent'], name='tickets_assigne_a21dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['customer'], name='tickets_custome_321035_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_at'], name='tickets_created_ed60df_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_delayed'], name='tickets_is_dela_8f4213_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_agent', 'status'], name='tickets_assigne_483f5f_idx'),
        ),
        migrations.AddIndex(
            model_name='responsetimetracking',
            index=models.Index(fields=['agent'], name='response_ti_agent_i_2372a4_idx'),
        ),
        migrations.AddIndex(
            model_name='responsetimetracking',
            index=models.Index(fields=['is_delayed'], name='response_ti_is_dela_ffcf80_idx'),
        ),
        migrations.AddIndex(
            model_name='responsetimetracking',
            index=models.Index(fields=['created_at'], name='response_ti_created_18926b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagesearchindex',
            index=models.Index(fields=['customer'], name='message_sea_custome_249f1b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeliverylog',
            index=models.Index(fields=['message'], name='message_del_message_a8469e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagedeliverylog',
            index=models.Index(fields=['created_at'], name='message_del_created_702ada_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ticket'], name='messages_ticket__a98e1c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender_type'], name='messages_sender__1fa575_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['created_at'], name='messages_created_919c58_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['whatsapp_message_id'], name='messages_whatsap_4d16c3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx'),
        ),
        migrations.AddIndex(
            model_name='globaltemplate',
            index=models.Index(fields=['is_active'], name='global_temp_is_acti_472ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='globaltemplate',
            index=models.Index(fields=['category'], name='global_temp_categor_d844e5_idx'),
        ),
        migrations.AddIndex(
            model_name='customertag',
            index=models.Index(fields=['customer', 'tag'], name='customer_ta_custome_eddb84_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customertag',
            unique_together={('customer', 'tag')},
        ),
        migrations.AddIndex(
            model_name='customersatisfaction',
            index=models.Index(fields=['agent'], name='customer_sa_agent_i_38ce96_idx'),
        ),
        migrations.AddIndex(
            model_name='customersatisfaction',
            index=models.Index(fields=['rating'], name='customer_sa_rating_6afc79_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['customer'], name='customer_no_custome_b06835_idx'),
        ),
        migrations.AddIndex(
            model_name='customernote',
            index=models.Index(fields=['created_at'], name='customer_no_created_9353bf_idx'),
        ),
        migrations.AddIndex(
            model_name='autoreplytrigger',
            index=models.Index(fields=['is_active'], name='auto_reply__is_acti_075480_idx'),
        ),
        migrations.AddIndex(
            model_name='autoreplytrigger',
            index=models.Index(fields=['trigger_keyword'], name='auto_reply__trigger_5b0494_idx'),
        ),
        migrations.AddIndex(
            model_name='agenttemplate',
            index=models.Index(fields=['is_active'], name='agent_templ_is_acti_dd994f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agenttemplate',
            unique_together={('agent', 'name')},
        ),
        migrations.AddIndex(
            model_name='agentkpimonthly',
            index=models.Index(fields=['month'], name='agent_kpi_m_month_8c2f26_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentkpimonthly',
            unique_together={('agent', 'month')},
        ),
        migrations.AddIndex(
            model_name='agentkpi',
            index=models.Index(fields=['kpi_date'], name='agent_kpi_kpi_dat_14384f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentkpi',
            unique_together={('agent', 'kpi_date')},
        ),
        migrations.AddIndex(
            model_name='agentdelayevent',
            index=models.Index(fields=['agent'], name='agent_delay_agent_i_94cc83_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdelayevent',
            index=models.Index(fields=['created_at'], name='agent_delay_created_2aec6b_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['status'], name='agents_status_f5ff61_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_online'], name='agents_is_onli_350001_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['current_active_tickets'], name='agents_current_55863b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user'], name='activity_lo_user_id_ef3d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='activity_lo_action_f14761_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='activity_lo_created_8906e2_idx'),
        ),
    ]
