# Generated by Django 4.2.7 on 2025-10-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='whatsapp_status',
            new_name='delivery_status',
        ),
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='outgoing', max_length=10),
        ),
    ]
