# Generated by Django 5.2.7 on 2025-11-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('web', 'Web'), ('mobile', 'Mobile App'), ('other', 'Other')], default='whatsapp', max_length=20),
        ),
    ]
