# Generated by Django 4.2.7 on 2025-11-02 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_add_message_queue_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_ticket', 'New Ticket Assigned'), ('new_message', 'New Message'), ('ticket_transferred', 'Ticket Transferred'), ('ticket_delayed', 'Ticket Delayed'), ('mention', 'Mentioned')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='conversations.agent')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conversations.customer')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='conversations.ticket')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'is_read'], name='notificatio_agent_i_4bb7e8_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
