# Generated by Django 4.2.7 on 2025-11-02 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
