# Generated by Django 4.2.25 on 2025-11-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0008_delete_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="category_selected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
