# Generated by Django 4.2.25 on 2025-11-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0009_ticket_category_selected_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="break_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agent",
            name="is_on_break",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="agent",
            name="total_break_minutes_today",
            field=models.IntegerField(default=0),
        ),
    ]
