# Generated by Django 4.2.25 on 2025-11-10 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0010_agent_break_started_at_agent_is_on_break_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentkpi",
            name="break_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="agentkpi",
            name="total_break_time_seconds",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AgentBreakSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_start_time", models.DateTimeField()),
                ("break_end_time", models.DateTimeField(blank=True, null=True)),
                ("break_duration_seconds", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="break_sessions",
                        to="conversations.agent",
                    ),
                ),
            ],
            options={
                "db_table": "agent_break_sessions",
                "indexes": [
                    models.Index(
                        fields=["agent"], name="agent_break_agent_i_1f08b0_idx"
                    ),
                    models.Index(
                        fields=["break_start_time"],
                        name="agent_break_break_s_40bef6_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="agent_break_created_2afb7f_idx"
                    ),
                ],
            },
        ),
    ]
