# Generated by Django 5.1.2 on 2025-11-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0011_agentkpi_break_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_algorithm', models.CharField(choices=[('least_loaded', 'Least Loaded'), ('round_robin', 'Round Robin'), ('random', 'Random')], default='least_loaded', max_length=20)),
                ('delay_threshold_minutes', models.IntegerField(default=3)),
                ('default_max_capacity', models.IntegerField(default=10)),
                ('work_start_time', models.TimeField(default='09:00')),
                ('work_end_time', models.TimeField(default='17:00')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
            },
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('ptt', 'Voice Message'), ('video', 'Video'), ('file', 'File'), ('interactive', 'Interactive'), ('template', 'Template')], default='text', max_length=20),
        ),
    ]
