# Generated by Django 5.1.2 on 2025-11-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0012_systemsettings_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin'), ('qa', 'QA (Quality Assurance)'), ('supervisor', 'Supervisor'), ('manager', 'Manager')], max_length=10),
        ),
    ]
