# Generated by Django 4.2.7 on 2025-11-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='direction',
            field=models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], default='outgoing', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('ptt', 'Voice Message'), ('video', 'Video'), ('file', 'File'), ('interactive', 'Interactive'), ('template', 'Template')], default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Agent'), ('admin', 'Admin'), ('system', 'System')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='delay_threshold_minutes',
            field=models.IntegerField(default=1),
        ),
    ]
