# Generated by Django 4.2.7 on 2025-11-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0014_alter_message_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttemplate',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agenttemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globaltemplate',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='globaltemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
